### ISSUE TITLE
Border around the board

### ISSUE THREAD

**Issue by 9glenda** [MDLC01/board-n-pieces#3]
I am not sure rather that's possible to do using typst since im pretty new to to typst.
![image](https://github.com/MDLC01/board-n-pieces/assets/69043370/a7c842f2-24f2-4697-89a2-0d497f881da2)
the boarder should be like in this image. Just a visual separation between the coordinates and the board.

**Comment by MDLC01** [comment]
I want to add more board customization features. This is one of them.
